### PR TITLE
User story/2/task/20/initialize socket io

### PR DESCRIPTION
**Pull request by jeph**
Implement #20 

Heroku deploy needs to be worked after this push as I've stripped the excess dependencies from the frontend now that we're deploying on Netlify. 

Backend is configured for ES6 syntax with Socket IO and Eslint with Standard js rules.

### CODE REVIEW

**Comment by jeph** [comment]
Heroku has been configured to deploy just the backend although app reviews still do not work.

**Comment by EricSihaoLin** [comment]
You might need to change the Procfile that is present in the root of the repo.
That's the command that Heroku uses to launch the instance.

**Comment by jeph** [comment]
> You might need to change the Procfile that is present in the root of the repo.
> That's the command that Heroku uses to launch the instance.

I've added a buildpack that strips away everything except the backend folder so we can just rely on the node js buildpack. The problem with the build right now is that I didn't configure babel to build the project so I'm doing that now.

**Comment by jeph** [comment]
@EricSihaoLin @rebeccahom @dz1358 

### App reviews are working and Heroku deploys are working. The PR should be good to merge into master. 

Also @EricSihaoLin, I've noticed you're fronting the bill for our app reviews and backend deploys yourself. App reviews don't support free dynos on Heroku but they're something we don't necessarily need as we can run tests in Travis and PR deploys are useful but not required. I would consider just removing them all together as it's really not fair to have you pay for it all by yourself.

You can also get a free hobby dyno from the GitHub Student Pack so we don't need to be paying for our prod deploy either.

**Comment by EricSihaoLin** [comment]
@jeph The Heroku offer with 1 free dyno is based on availability. I applied for it but was never credited to my account.

Review apps are cheap, so are the hobby dynos, and I don't mind because this is basically a chunk of change. Don't pay attention to it.

**Pull request merged**
