### PR TITLE
Socket.io Canvas Sync

### PR DESCRIPTION
**Pull request by EricSihaoLin**
This branch aims to implement rudimentary canvas sync between all clients. 

Currently, it allows all inputs from all clients to broadcast to all other clients, all the time. Super bad design, but it's a jumping-off point.

Please review, but do not merge yet.

### CODE REVIEW

**Comment by jeph** [comment]
Implement #90

**Comment by jeph** [comment]
Yeah it looks good 👍 
It might be nice to have our frontend hit our heroku server when deployed but have it hit localhost in our local environments just so we won't have to pull request everytime we want to test our frontend backend integration.

**Comment by rebeccahom** [comment]
Also don't forget to reference the issues that this is relevant to: #48

**Comment by EricSihaoLin** [comment]
@jeph I have made it aware of the environment in the canvas. We might want to separate this in the future too off the drawing canvas, but I don't quite know how to do it yet.

@rebeccahom The console.logs has been removed from client, but I will not remove it from the server because that is very useful on socket.io side for now.

I also added the `setup-devserver.sh` and `push-devserver.sh` scripts in case if you want to push to the staging server after your commit.

**Comment by jeph** [comment]
> @jeph I have made it aware of the environment in the canvas. We might want to separate this in the future too off the drawing canvas, but I don't quite know how to do it yet.
> 
> @rebeccahom The console.logs has been removed from client, but I will not remove it from the server because that is very useful on socket.io side for now.
> 
> I also added the `setup-devserver.sh` and `push-devserver.sh` scripts in case if you want to push to the staging server after your commit.

Awesome! 👍

**Pull request merged**
